--- #YAML:1.0
name:               Dpchrist-Timestamp
version:            1.021
abstract:           generate time stamps
author:
    - David Paul Christensen <dpchrist@holgerdanske.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 1.08
    Config:               0
    Data::Dumper:         2.12114
    Dpchrist::LangUtil:   1.018
    Exporter:             5.62
    ExtUtils::MakeMaker:  6.54
    File::Spec::Functions:  3.2501
    Test::Compile:        0.1
    Test::Manifest:       1.22
    Test::More:           0.72
    Test::Pod:            1.4
    Test::Prereq:         1.037
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
